name: Deploiement Local VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build et Déploiement Docker
    runs-on: self-hosted
    
    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Arrêt des conteneurs existants
        run: |
          docker-compose down || true
          docker system prune -f || true

      - name: Build et démarrage des conteneurs
        run: |
          docker-compose build --no-cache
          docker-compose up -d

      - name: Vérification du déploiement
        run: |
          docker-compose ps
          docker-compose logs -f
